### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by CrashLaker** [yannlambret/vizceral-example-backend#1]
Hi @yannlambret 
Sorry I'm still trying to understand how vizceral internal's work from the sample_data_simple.json to how the whole thing gets updated.

I'm trying to run your program but I'm getting 
`404 not found`  

the next step was to point the url inside beginSampleData() in trafficFlow.jsx to localhost:9092 right?

thanks in advance

**Comment by yannlambret** [comment]
Hi @CrashLaker,

At the time being, I had to introduce a small change in the frontend for it to handle communication with websockets. You can find the details here: https://github.com/yannlambret/vizceral-example/commit/f2c2da40d8844dda4dd9bb275da9daf15f521be6

Have a nice day.

**Comment by CrashLaker** [comment]
It worked!!

thank you so much :)
